
function loadDistributorsView(){
    document.getElementById("main-content").innerHTML =`
        <div class="container-fluid disti-view mt-2">
            <div class="header">
                <h2 class="">Performance</h2>
                <p class="fs-6"><small>Monitor Distributor Efficiency and Sales Impact</small></p>
            </div>    
            <div class="d-flex justify-content-end mt-2">
                <button class="btn btn-outline-success fw-medium" onclick="loadPage('distributors-list', this)">View All</button>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card shadow mt-2">
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Distributor</th>
                                    <th>Location</th>
                                    <th>Business Generated</th>
                                    <th>Revenue(₹)</th>
                                    <th>Status</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>Green Valley Dairy Distributors</td>
                                    <td>Boduppal, Hyd</td>
                                    <td>200 Liters</td>
                                    <td>21,000</td>
                                    <td><span class="badge bg-success-subtle text-success">Active</span></td>
                                </tr>
                                <tr>
                                    <td>Fresh Milk Distributors</td>
                                    <td>Ramanthapur, Hyd</td>
                                    <td>100 Liters</td>
                                    <td>10,500</td>
                                    <td><span class="badge bg-success-subtle text-success">Active</span></td>
                                </tr>
                                <tr>
                                    <td>Organic Dairy Distributors</td>
                                    <td>Tharnaka, Hyd</td>
                                    <td>180 Liters</td>
                                    <td>19,000</td>
                                    <td><span class="badge bg-success-subtle text-success">Active</span></td>
                                </tr>
                                <tr>
                                    <td>Golden Milk Distributors</td>
                                    <td>LB Nagar, Hyd</td>
                                    <td>90 Liters</td>
                                    <td>8,500</td>
                                    <td><span class="badge bg-success-subtle text-success">Active</span></td>
                                </tr>
                                <tr>
                                    <td>Pure Dairy Distributors</td>
                                    <td>Boinpally, Hyd</td>
                                    <td>110 Liters</td>
                                    <td>12,000</td>
                                    <td><span class="badge bg-success-subtle text-success">Active</span></td>
                                </tr>
                                <tr>
                                    <td>Healthy Farms Distributors</td>
                                    <td>Begumpet, Hyd</td>
                                    <td>80 Liters</td>
                                    <td>7,000</td>
                                    <td><span class="badge bg-success-subtle text-success">Active</span></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
       
            <div class="row">
                <div class="col-md-6">
                    <div class="card b-card shadow p-3 mt-3">
                        <h4 class="mx-3">Total Business Generated</h4>
                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center">
                            <h3>20,000 Liters</h3>
                            <span class="material-icons-outlined fs-1 fw-bold text-success">trending_up</span>
                            </div>
                            <p class="fw-medium">Total business generated by all distributors.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card r-card shadow p-3 mt-3">
                        <h4 >Total Revenue Generated</h4>
                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center">
                            <h3>₹17,10,000</h3>
                            <span class="material-icons-outlined fs-1 fw-bold text-success">trending_up</span>
                            </div>
                            <p class="fw-medium">Total revenue contributed by all distributors.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    `;
}